version: 2.0
jobs:
  package:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Gradle Jar
          command: gradle jar
      - store_artifacts:
          path: build/libs
          destination: build
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Test
          command: gradle test
      - store_test_results:
          path: build/test-results
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - package:
        requires:
          - test