version: 2.0
jobs:
  package:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Gradle Jar
          command: gradle jar
      - store_artifacts:
          path: build/libs
          destination: build
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Test
          command: gradle test -i
      - store_test_results:
          path: build/test-results
      - persist_to_workspace:
          root: .
          paths:
              - .
  dockerize:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t $DOCKER_USER/myapp:$CIRCLE_SHA1 .
      - run: docker push $DOCKER_USER/myapp:$CIRCLE_SHA1

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - package:
          requires:
            - test
      - dockerize